### ISSUE TITLE
Go live

### ISSUE THREAD

**Issue by benbc** [opensafely-core/output-explorer#118]
These are the steps we need to carry out to get the first one or two reports published and visible to the general public. We have several candidates for the first report:

* #144 
* #143 
* #50 

When we're ready to publish a single report, whichever it is, we need to:

- [x] Mark all reports as draft (in the Admin UI)
- [x] Publish the one report that's ready (see issues linked above)
- [x] Turn off HTTP Auth in production (see README for details)

**Comment by richiecroker** [comment]
@benbc looks good, I can't see anything missing.

**Comment by rebkwok** [comment]
LGTM
