### ISSUE TITLE
Link to the correct branch of the repo

### ISSUE THREAD

**Issue by benbc** [opensafely-core/output-explorer#150]

**Comment by rebkwok** [comment]
@benbc Do you remember what this issue was about?  Is it done?

**Comment by benbc** [comment]
@rebkwok I do!

[This report](https://reports.opensafely.org/admin/reports/report/9/change/) specifies the `1.17` branch, which is where we get the content from, but the source link [here](https://reports.opensafely.org/reports/vaccine-coverage-15-jun-2021/) links to the default branch.

The idea was to link to the "correct" branch instead.

**Comment by rebkwok** [comment]
So it's literally just updating the source link in the admin from https://github.com/opensafely/nhs-covid-vaccination-coverage to https://github.com/opensafely/nhs-covid-vaccination-coverage/tree/1.17?  Seems like an easy win :)

**Comment by rebkwok** [comment]
Done!
