### ISSUE TITLE
Investigate nbconvert html output template options

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/output-explorer#23]
Output HTML files have typically been converted using `nbconvert` with the default template option, which makes it look as much like a jupyter notebook as possible. Options are:

> `--template lab (default)`
> A full static HTML render of the notebook. This looks very similar to the jupyter lab interactive view.
> 
> `--template classic`
> Simplified HTML, using the classic jupyter look and feel.
> 
> `--template basic`
> Base HTML, rendering with minimal structure and styles.

Basic html may be enough to allow customising the styling, or there's an option to use a custom template
[https://nbconvert.readthedocs.io/en/latest/customizing.html](https://nbconvert.readthedocs.io/en/latest/customizing.html)

Would require whoever's running nbconvert to use the new option, whatever that may be.

**Comment by benbc** [comment]
Our current preference is for the `basic` template, with charts as embedded bitmaps.

The necessary changes to the SRO Measures notebook to fall in line with that are in https://github.com/opensafely/SRO-Measures/pull/18.

**Comment by benbc** [comment]
Testing: this is successful if the newly-reformatted SRO Measures output can be successfully styled by @tomodwyer.
