### ISSUE TITLE
Databases Build Report 500ing

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/output-explorer#321]
We're seeing a 500 error on [the TPP Databases Build report page](https://reports.opensafely.org/reports/opensafely-tpp-database-builds/), [stack trace in Sentry](https://sentry.io/organizations/ebm-datalab/issues/3336126337/?project=5756541&query=is%3Aunresolved).

The `process_html()` function is receiving None from `GitHubReport().get_html()`.

**Comment by ghickman** [comment]
The response from the Contents API doesn't return an errors key (or a 403/404) when 1MB < file size < 100MB so we can't trigger the `GithubAPIFileTooLarge` exception.

We can check for an empty `content` value but that breaks how `get_parent_contents` uses the function (ideally we'd not layer wrappers like this).

Ideally we would issue a new request with [the raw media type](https://docs.github.com/en/rest/repos/contents#custom-media-types-for-repository-contents) to the same URL since we're unlikely to be getting 100MB files.

**Comment by lucyb** [comment]
Can this be closed now?

**Comment by ghickman** [comment]
Fixed in opensafely-core/osgithub#56
