### ISSUE TITLE
Documentation for researchers

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/output-explorer#33]
- how to generate html reports/outputs for OE (nbconvert options, custom templates, guidelines on not including billions of SVGs etc)
- Adding a new Output in the admin (assuming researchers will do that)
- Updating

**Comment by benbc** [comment]
- [ ] use basic format for `nbconvert`
- [ ] render charts as inline bitmaps
- [ ] don't use `print()` to output text from code blocks unless you want it to look like code -- use `display(Markdown()` instead

The SRO Measures code has examples of all these changes, I can dig out the actual commits for details.

**Comment by benbc** [comment]
https://github.com/ebmdatalab/team-manual/pull/83
