### ISSUE TITLE
SPIKE Custom styling for pilot

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/output-explorer#363]
For the pilot with a small number of external users, it would be useful to know if there is an easy way to style the reports that are generated and what options we might have (e.g a banner with their logo on one part of the report or something more comprehensive).

As it's a pilot, it shouldn't involve building much custom code or anything that's going to involve much time (for researchers or devs) and would be something we could expand upon later.

### Acceptance criteria
* Details of options for styling of reports for the pilot project

**Comment by tomodwyer** [comment]
# Spike outputs

Half-day investigation.

## UI Example

https://user-images.githubusercontent.com/24863179/188125634-f227a800-964f-42bc-aa84-ebdf96b60e87.mp4

---

<img width="997" alt="CleanShot 2022-09-02 at 11 59 56@2x" src="https://user-images.githubusercontent.com/24863179/188125748-bfdceec3-bb97-4326-842d-941df8462d9e.png">

---

<img width="1021" alt="CleanShot 2022-09-02 at 12 00 02@2x" src="https://user-images.githubusercontent.com/24863179/188125750-0ef3446a-ceac-4a08-8125-17d0e7905bb9.png">

## Logic

If a report is marked as external, the heading box and above report box should be visible. The admin section should show the fields to populate information for these sections.

## Admin fields

The following fields would need to be added to allow admins to add the relevant information.

- **Mark as external** – checkbox to trigger the following required fields
- **Organisation** – `<select>` element containing all partner organisations
  - **Logo**
  - **Homepage link**
- **Partner description** – `<textarea>` element to add the initial description ("Lorem ipsum" text in the above video/screenshot)

**Comment by tomodwyer** [comment]
Spike output now covered by:

- https://github.com/opensafely-core/output-explorer/issues/376
- https://github.com/opensafely-core/output-explorer/issues/377
