### ISSUE TITLE
Refactor requests_cache for github api calls only

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/output-explorer#46]
Currently we monkeypatch requests with requests_cache everywhere, which means we have to manually disable it for the nhs id calls, and it will probably cause weirdness later.  It was done that way because it was the easiest way to convert the existing github code (using PyGithub) to use cached requests, but should be refactored so that we have more visible control over the request caching, and limit it to github calls only

**Comment by benbc** [comment]
@rebkwok Looks like this is done, so I'm closing. Please reopen if I'm wrong.
