### ISSUE TITLE
Publish Database schema/builds reports

### ISSUE THREAD

**Issue by benbc** [opensafely-core/output-explorer#50]
Will maintains a repo with notebooks reporting on the contents of the TRE databases. We would like to publish the [database builds](https://github.com/opensafely/database-notebooks/blob/master/notebooks/database-builds.ipynb) and [database schema](https://github.com/opensafely/database-notebooks/blob/master/notebooks/database-schema.ipynb) notebooks as reports.

These notebooks are not run using the OpenSAFELY command line tool, Will runs the notebooks directly on the servers and then releases them as outputs in the normal way.

Plan is to have a Github Action which exports the released notebooks as HTML when Will checks them in (and then itself checks in the results so OpenSAFELY Reports can pick them up).

 - [x] Merge https://github.com/opensafely/database-notebooks/pull/20 to automatically export notebooks as HTML.
 - [x] Wait for the HTML exports to be generated automatically.
 - [x] Create draft reports.
 - [x] Check drafts with Will.
 - [x] Get TomO to do a quick check of the formatting.
 - [x] Strip code chunks out of the notebook while rendering into HTML.
 - [ ] Wait for wording to be agreed and updated.
 - [ ] Make reports public.

**Comment by benbc** [comment]
https://ebmdatalab.slack.com/archives/C31D62X5X/p1622625734356200

**Comment by benbc** [comment]
This repo doesn't use the `project.yaml`. Will runs the notebooks on the server by hand and releases them _as notebooks_. The `project.yaml` and HTML outputs in the repo are the results of earlier experiments to try to get things working through that toolchain.

So the authoritative content is the notebook. We can script converting them to HTML for consumption by OpenSAFELY Reports -- but will need to do that without executing them because that's only possible on the server. Then whenever Will releases updated notebooks we can do the conversion again.

Idea: can we use a Github action for this? It would need to trigger whenever the notebook changes _and check in the results_.

**Comment by benbc** [comment]
@wjchulme Here is the issue I'm using to track this.

**Comment by benbc** [comment]
https://github.com/opensafely/database-notebooks/pull/20

**Comment by rebkwok** [comment]
@benbc Is there still something pending on this one?  The database reports are published now, and your github action to generate and commit the notebook html is merged.

**Comment by benbc** [comment]
There was some last minute worry about making them public, but I suppose that it must have been overcome. Nothing else needed that I'm aware of.
