### ISSUE TITLE
Provide contact info for reports

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/output-explorer#96]
A link, contacting team@opensafely.org should be clear for each report.

This could be present in the title div of each report or could be signposted in the nav bar.  @brianmackenna what do you think?  Will this email always be the same?

**Comment by brianmackenna** [comment]
Thanks @LFISHER7 this sounds good. I'm very keen  that our contact details are very prominent to users - our experience with OpenPrescribing has shown that we get

- helpful feedback about whats good/whats bad
- people will examine codelists in particular and give us direct feedback which help us tweak measures
- suggestions for new useful features
- stories about how people are using the reports for something we never even dreamed of when we started (e.g. OP [dexamethasone](https://www.thedatalab.org/blog/67/high-dose-dexamethasone/)) 

I think for now the OpenSAFELY team will be contact for every report. I can see a point in the future where an external person produces a report and the user may need to contact
a) OpenSAFELY team for general feedback
B) external person for specific feedback
